# Uncomment this line to define a global platform for your project
platform :ios, '15.5.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# 权限配置开始
  config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      '$(inherited)',

      ## 仅允许写入日历的权限（iOS 16 及以下）
      'PERMISSION_EVENTS=1',

      ## 允许完全访问日历的权限（iOS 17及以上）
      'PERMISSION_EVENTS_FULL_ACCESS=1',

      ## 提醒事项权限
      'PERMISSION_REMINDERS=1',

      ## 联系人权限
      'PERMISSION_CONTACTS=1',

      ## 相机权限
      'PERMISSION_CAMERA=1',

      ## 麦克风权限
      'PERMISSION_MICROPHONE=1',

      ## 语音识别权限
      'PERMISSION_SPEECH_RECOGNIZER=1',

      ## 照片权限
      'PERMISSION_PHOTOS=1',

      ## 位置权限组（包括始终、使用中）
      'PERMISSION_LOCATION=1',

      ## 通知权限
      'PERMISSION_NOTIFICATIONS=1',

      ## 媒体库权限
      'PERMISSION_MEDIA_LIBRARY=1',

      ## 传感器权限
      'PERMISSION_SENSORS=1',

      ## 蓝牙权限
      'PERMISSION_BLUETOOTH=1',

      ## 应用跟踪透明度权限
      'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

      ## 关键警报权限
      'PERMISSION_CRITICAL_ALERTS=1'
    ]
    # 权限配置结束
  end


# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#     target.build_configurations.each do |config|
#       deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
#       if !deployment_target.nil? && !deployment_target.empty? && deployment_target.to_f < 12.0
#         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5.0'
#       end
#     end
#   end
# end

# post_install do |installer|
#     installer.pods_project.targets.each do |target|
#   		flutter_additional_ios_build_settings(target)
#  		    target.build_configurations.each do |config|
#          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
#   	    '$(inherited)',
#       	'PERMISSION_MICROPHONE=1',
#     ]
#     end
#   end
# end
